name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      PORT: ${{ secrets.PORT }}
      ALTERNATIVE_PORT: ${{ secrets.ALTERNATIVE_PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      DEFAULT_DOMAIN: ${{ secrets.DEFAULT_DOMAIN }}
      DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
      SOCKET_TIMEOUT: ${{ secrets.SOCKET_TIMEOUT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          export PATH=$PATH:/home/nichld/.npm-global/bin
          npm install

      - name: Build
        run: npm run build

      - name: Start app
        run: |
          export PATH=$PATH:/home/nichld/.npm-global/bin
          pm2 delete helpdesk || true
          pm2 start npm --name helpdesk -- start
