name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      PORT: ${{ secrets.PORT }}
      ALTERNATIVE_PORT: ${{ secrets.ALTERNATIVE_PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      DEFAULT_DOMAIN: ${{ secrets.DEFAULT_DOMAIN }}
      DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
      SOCKET_TIMEOUT: ${{ secrets.SOCKET_TIMEOUT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy Application
        run: |
          pm2 delete helpdesk || true
          pm2 start npm --name "helpdesk" -- start
